apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jokeapp-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/EbYVarghese18/DevOps_Project_03.git
    targetRevision: HEAD
    path: jokeapp-green
  destination: 
    server: https://kubernetes.default.svc
    namespace: jokeapp
    
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true