apiVersion: v1
kind: Service
metadata:
  name: jokeapp-blue-service
  labels:
    app: jokeapp-blue
spec:
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8001
  selector:
    app: jokeapp-green
  type: NodePort