apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokeapp-green-deployment
  labels:
    app: jokeapp-green
spec:
  replicas: 4
  selector:
    matchLabels:
      app: jokeapp-green
  template:
    metadata:
      labels:
        app: jokeapp-green
    spec:
      containers:
        - name: jokeapp-green
          image: ebinvarghese/jokeapp-green:latest
          ports:
            - containerPort: 8001
